### PR TITLE
MODIFY Add optional ssl support from URL scheme

### PR DESCRIPTION
**Pull request by wobbals**

### CODE REVIEW

**Comment by katta** [comment]
Thanks wobbals for the pull request.

**Comment by wobbals** [comment]
Thanks for the merge! I wasn't sure if I should also bump the rubygem version info, or if that's something you need to push manually.

**Comment by katta** [comment]
I will take care of it, will bump up the version and push it to the
rubygems.org today.

Thanks,

**Comment by katta** [comment]
Pushed new version 0.0.6 of gem to rubygems.org that has https support

**Pull request merged**
